membersrvc:
   image: hyperledger/fabric-membersrvc
   ports:
     - "7054:7054"
   command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7053:7053"
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENABLED=false
    - CORE_SECURITY_ENROLLID=vp
    - CORE_SECURITY_ENROLLSECRET=f3489fy98ghf
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start --peer-chaincodedev"
